name: SAST/SCA Security Analysis
on:
  workflow_call:
    outputs:
      scan-result:
        description: "SAST/SCA scan summary"
        value: ${{ jobs.summary.outputs.result }}

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  # 🚧 REPLACE THE JOB SECTION WITH WORKSHOP CONTENT! 🚧
  # Copy from: workshop/code_scan/sast/{tool}/workflow.yml 
  sast-scan:
    name: "🚧 SAST Scan - Placeholder"
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.placeholder.outputs.result }}
    steps:
      - name: Workshop Placeholder
        id: placeholder
        run: |
          echo "🚧 Replace this job with content from workshop/code_scan/sast/{tool}/workflow.yml!"
          echo "This will implement: SAST scan with your chosen tool"
          echo "result=workshop-placeholder" >> "$GITHUB_OUTPUT"

  # 🚧 REPLACE THE JOB SECTION WITH WORKSHOP CONTENT! 🚧
  # Copy from: workshop/code_scan/sca/{tool}/workflow.yml
  sca-scan:
    name: "🚧 SCA Scan - Placeholder"
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.placeholder.outputs.result }}
    steps:
      - name: Workshop Placeholder
        id: placeholder
        run: |
          echo "🚧 Replace this job with content from workshop/code_scan/sca/{tool}/workflow.yml!"
          echo "This will implement: SCA scan with your chosen tool"
          echo "result=workshop-placeholder" >> "$GITHUB_OUTPUT"

  codeql-scan:
    name: CodeQL SAST Scan
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.scan-result.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@f1f6e5f6af878fb37288ce1c627459e94dbf7d01 # v3.30.1
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        id: codeql-tool
        uses: github/codeql-action/analyze@f1f6e5f6af878fb37288ce1c627459e94dbf7d01 # v3.30.1

      - name: Wait for GitHub to process results
        run: sleep 30

      - name: Check for CodeQL security alerts
        id: check-findings
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use gh CLI to check for code scanning alerts
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            ALERTS=$(gh api "repos/${{ github.repository }}/code-scanning/alerts?state=open&pr=${{ github.event.number }}&tool_name=CodeQL" 2>/dev/null || echo "[]")
          else
            ALERTS=$(gh api "repos/${{ github.repository }}/code-scanning/alerts?state=open&tool_name=CodeQL" 2>/dev/null || echo "[]")
          fi
          
          ALERT_COUNT=$(echo "$ALERTS" | jq '. | length' 2>/dev/null || echo "0")
          