name: Deploy Infrastructure

on:
  workflow_call:
    outputs:
      deployment-result:
        description: "Infrastructure deployment result"
        value: ${{ jobs.deploy-infra.outputs.result }}

jobs:
  deploy-infra:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }} 
    outputs:
      result: ${{ steps.deploy.outputs.result }}
    steps:
      - name: Deploy infrastructure
        id: deploy
        env:
          ENVIRONMENT: ${{ github.ref_name }}
        run: |
          echo "🚀 Deploying infrastructure to $ENVIRONMENT..."
          echo "🏗️ Terraform plan -var environment=$ENVIRONMENT"
          echo "🏗️ Terraform apply -auto-approve"
          echo "result=deployed" >> "$GITHUB_OUTPUT"
          echo "✅ Infrastructure deployed successfully"

      - name: Infrastructure Summary
        env:
          ENVIRONMENT: ${{ github.ref_name }}
        run: |
          echo "🏗️ Infrastructure Deployment Summary:"
          echo "- Environment: $ENVIRONMENT"
          echo "- Region: us-east-1"
          echo "- Resources: VPC, Subnets, Security Groups, EC2"
          echo "- Status: Healthy"
