name: Integration Test

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to test"
        required: true
        type: string
      app-url:
        description: "Application URL to test"
        required: true
        type: string
    outputs:
      integration-test-result:
        description: "Integration test result"
        value: ${{ jobs.integration-test.outputs.result }}

jobs:
  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      result: ${{ steps.integration-test.outputs.result }}
    steps:
      - name: Integration Test
        id: integration-test
        run: |
          echo "🚀 Running integration test..."
          echo "bip, bop, bup"
          echo "bip, bop, bup"
          echo "result=passed" >> "$GITHUB_OUTPUT"
          echo "✅ Integration test passed successfully"

      - name: Integration Test Summary
        env:
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          echo "🏗️ Integration Test Summary:"
          echo "- Environment: $ENVIRONMENT"
          echo "- Status: Healthy"
