name: Pipeline Security Scan

on:
  workflow_call:
    outputs:
      scan-result:
        description: "Pipeline scan result"
        value: ${{ jobs.pipeline-scan.outputs.result }}

jobs:
  # 🚧 REPLACE THIS ENTIRE 'jobs:' SECTION WITH WORKSHOP CONTENT! 🚧
  # Copy from: workshop/pipeline_scan/{tool}/workflow.yml


  zizmor:
    name: Run zizmor 🌈
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read # only needed for private repos
      actions: read # only needed for private repos
    steps:
      - name: Checkout repository
        uses: actions/checkout@03af241587ab470b23340e354be5682ba0850474  #this is the latest branch
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@main
        with:
          min-severity: "high"